### ISSUE TITLE
kwargs are sent to super class initializer that does not accept kwargs

### ISSUE THREAD

**Issue by oeoeaio** [dry-rb/dry-auto_inject#80]
## Describe the bug
When the class hierarchy includes a direct parent that splats args but whose own parent (i.e. grandparent of child) does not accept *any* kwargs, the current implementation for the kwargs strategy will still attempt to pass-through any kwargs not listed as dependencies of the parent to the grandparent, resulting in an ArgumentError.

## To Reproduce

The test I have added in # will fail without the corresponding update to the implementation.

## Expected behavior

We should still be able to use the default kwargs strategy for dependency injection even with two layers of dependency injection in the hierarchy and a super class that does not itself accept kwargs. (This may or may not be a valid expectation, but I could not find any documentation to contradict it).

## My environment

- Affects my production application: NO, but (for reasons not worth elaborating on here) is blocking upgrade of prod system to ruby 3
- Ruby version: 3.1.1
- OS: macOS

**Comment by ka8725** [comment]
Bumped into this bug on Ruby 3.4.4 Rails 7.2.2.1 combo.

Controller:

```ruby
class WebsvcController < ActionController::Base
  include Dry::Monads[:result]
  include BTG::Import[
    websvc_processing: 'orders.invoice.websvc_processing_service',
  ]

  def index
    invoice_service = websvc_processing.call(auth_header: hmac_header, request_body: request_body)
    # not relevant code
  end
end
```

Related trace (last X lines):

```
/lib/ruby/gems/3.3.0/gems/actionview-7.2.2.1/lib/action_view/rendering.rb:32:in `initialize'
/lib/ruby/gems/3.3.0/gems/actionview-7.2.2.1/lib/action_view/layouts.rb:363:in `initialize'
/lib/ruby/gems/3.3.0/gems/actionpack-7.2.2.1/lib/action_controller/metal/request_forgery_protection.rb:365:in `initialize'
/lib/ruby/gems/3.3.0/gems/actionpack-7.2.2.1/lib/action_controller/metal/instrumentation.rb:25:in `initialize'
/lib/ruby/gems/3.3.0/gems/activerecord-7.2.2.1/lib/active_record/railties/controller_runtime.rb:27:in `initialize'
/lib/ruby/gems/3.3.0/gems/dry-auto_inject-0.7.0/lib/dry/auto_inject/strategies/kwargs.rb:70:in `block (2 levels) in define_initialize_with_splat'
/lib/ruby/gems/3.3.0/gems/dry-auto_inject-0.7.0/lib/dry/auto_inject/strategies/kwargs.rb:22:in `new'
/lib/ruby/gems/3.3.0/gems/dry-auto_inject-0.7.0/lib/dry/auto_inject/strategies/kwargs.rb:22:in `block (2 levels) in define_new'
/lib/ruby/gems/3.3.0/gems/actionpack-7.2.2.1/lib/action_controller/metal.rb:335:in `dispatch'
```

I found this solution for now - do not use the autoinjector here:

```ruby
class WebsvcController < ActionController::Base
  include Dry::Monads[:result]

  def index
    websvc_processing = Orders::Invoice::WebsvcProcessingService.new
    invoice_service = websvc_processing.call(auth_header: hmac_header, request_body: request_body)
    # not relevant code
  end
end
```

**Comment by jonleighton** [comment]
The following implements a workaround for RSpec (actually, maybe this only affects `rspec-rails`, not `rspec` more generally):

``` ruby
module DryAutoInjectHelper
  # Workaround for https://github.com/dry-rb/dry-auto_inject/issues/80#issuecomment-3519771303
  def initialize(*args, **)
    super(*args)
  end
end

RSpec.configure do |config|
  config.include DryAutoInjectHelper
end
```

**Comment by alassek** [comment]
@oeoeaio I've made some significant changes in #97, could you verify whether you're still seeing this problem?
